### ISSUE TITLE
Make the script easy to port to other devices

### ISSUE THREAD

**Issue by Lanchon** [Lanchon/REPIT#10]

**Comment by MalcolmMcConnor** [comment]
Seems like the right issue to participate to get notified if this feature becomes relevant - I would like to use the script on the i9100G

**Comment by Lanchon** [comment]
committed first version of multi-device support

**Comment by Lanchon** [comment]
this is done, however some details remain:
- the future addition of encryption footer support will (trivially) break compatibility with previous device configuration files.
- this script is complex and requires a lot of support from the recovery runtime environment (for now).

on the i9100, only TWRP 2.8.7.0 supports the script. do you have said TWRP on the i9100G? thanks!

**Comment by MalcolmMcConnor** [comment]
Yes, i have this exact Recovery,

greetings,

Michael

Am 11. März 2016 11:48:44 MEZ, schrieb Lanchon notifications@github.com:

> this is done, however some details remain:
> - the future addition of encryption footer support will (trivially)
>   break compatibility with previous device configuration files.
> - this script is complex and requires a lot of support from the
>   recovery runtime environment (for now).
> 
> on the i9100, only TWRP 2.8.7.0 supports the script. do you have said
> TWRP on the i9100G? thanks!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Lanchon/REPIT/issues/10#issuecomment-195315158

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by MalcolmMcConnor** [comment]
But as of now there's no i9100g Support file in repit2\devices Folder. I guess you will announce once it's ready to test?

Am 11. März 2016 11:48:44 MEZ, schrieb Lanchon notifications@github.com:

> this is done, however some details remain:
> - the future addition of encryption footer support will (trivially)
>   break compatibility with previous device configuration files.
> - this script is complex and requires a lot of support from the
>   recovery runtime environment (for now).
> 
> on the i9100, only TWRP 2.8.7.0 supports the script. do you have said
> TWRP on the i9100G? thanks!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Lanchon/REPIT/issues/10#issuecomment-195315158

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Lanchon** [comment]
well the idea is that now anyone can easily port to other devices. but you need a device to actually do the port; i don't have an i9100g.

but i just made a device-dump tool (committed) for you and anyone who needs help in porting, or rather not port it themselves. you run it on your PC (windows or linux; windows untested) while you are connected via adb to your recovery. it creates an output text file from which i can obtain all the info i need to port to your device.

if you send me the file i will port the tool.

keep in mind that your recovery might not be complete enough for this tool. but i have an idea in the works to fix that.

thanks!

**Comment by MalcolmMcConnor** [comment]
After some fiddeling I managed to get the dump.sh on my device with 
minimaladb setup. Batch file is somehow not working.

Cannot create the /tmp/ directory needed, I did this with Total 
Commander and also copied the file there (filesystems needs to be rw and 
totalcommander does this for me.....

by executing:
1|root@GT-I9100G:/ # sh /tmp/dump.sh >/storage/sdcard1/Download/dump-out.txt
/tmp/dump.sh[5]: syntax error: 'newline' unexpected
1|root@GT-I9100G:/ #

I get this error....

Am 11.03.2016 um 19:39 schrieb Lanchon:

**Comment by Lanchon** [comment]
did you run the script via adb on recovery or on android? it must be run on the recovery you plan to use.

what platform is your PC?

**Comment by MalcolmMcConnor** [comment]
I did run it on Android - I wasn't aware it had to be run under recovery, sorry.  My PC is Windows 10 pro

Am 12. März 2016 21:07:09 MEZ, schrieb Lanchon notifications@github.com:

> did you run the script via adb on recovery or on android? it must be
> run on the recovery you plan to use.
> 
> what platform is your PC?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Lanchon/REPIT/issues/10#issuecomment-195802107

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Lanchon** [comment]
sorry, i wrote that on the original message but i should have made more of a point of it i think. anyway, if you can run the script i'll create the port.

**Comment by Lanchon** [comment]
i'm closing this because multi-device support in main code is done, and so far you are not providing the dump to make the port you want. but if you want to request a port, please open a new issue and attach the dump file. thanks!
