### ISSUE TITLE
Samsung Galaxy S5 G900F (klte)

### ISSUE THREAD

**Issue by BlauerKlausR** [Lanchon/REPIT#104]
device Samsung S5 SM-G900F  
device codename klte
recovery  twrp_3.3.1-0
kernel 3.4.113
rom lineage-16.0-20191222-nightly-klte-signed.zip
[repit-dump-SM-G900F.log](https://github.com/Lanchon/REPIT/files/4006922/repit-dump-SM-G900F.log)
is your device running the stock partition layout or is it already modified?: no modification

**Comment by Lanchon** [comment]
https://github.com/Lanchon/REPIT/issues/45
https://github.com/Lanchon/REPIT/issues/44
