### ISSUE TITLE
Request new device: NEXUS7 2012 - Grouper

### ISSUE THREAD

**Issue by osfrance** [Lanchon/REPIT#106]
Hi Lanchon, Thanks for your work, 
I need to extend my System partition for installing Gapps-pico on my device, here the informations :
Device: NEXUS 7 2012 - Grouper
Recovery: Official TWRP 3.3.1-0
Kernel: 3.1.10-nougat-g73db112469b
Rom: 14.1-20181209-UNOFFICIAL-aaopt-grouper
Dump: [repit-dump.log](https://github.com/Lanchon/REPIT/files/4604128/repit-dump.log)

Thanks a lot !

**Comment by Lanchon** [comment]
thanks!

please see #79.

your log shows same weirdness, sorry.

**Comment by osfrance** [comment]
Ok thanks, I finally shrink gapp-nano package ...
