### ISSUE TITLE
OnePlus One (bacon)

### ISSUE THREAD

**Issue by gaucholoncoy** [Lanchon/REPIT#108]
hello,  I apreciated your great 
[repit-dump.log](https://github.com/Lanchon/REPIT/files/5048522/repit-dump.log)
work, 
I attached  the repit-dump.log from an old ONEPLUS ONE with android 9 (lineageos 16)
I want to flash the new version but no space in the system partition and I need to expand to 1.G G the system partition.

I used TWRP 3.4 

No repartitioning was done.

**Comment by Lanchon** [comment]
your device might be affected by #55.

**Comment by Lanchon** [comment]
https://github.com/Lanchon/REPIT/issues/33
