### ISSUE TITLE
partitioning ulefone ulefone note 7

### ISSUE THREAD

**Issue by sirkev** [Lanchon/REPIT#109]
PS C:\adb> adb pull /tmp/repit-dump.log
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
remote object '/tmp/repit-dump.log' does not exist
 am getting this yet i have flashed the dump-zip 

am using TWRP 3.4.0 on ulefone note 7

**Comment by Lanchon** [comment]
this after flashing repit-dump? then pull twrp's log and post it (after running repit- dump).

**Comment by sirkev** [comment]
Alright , but is it possible to repartition ulefone note 7 ... because am
just from unbricking my device after a failed upgrade to lineage 17.1
It's a good thing I had taken a back up
