### ISSUE TITLE
PR to une github lanchon/REPIT for samsung note 1 gt n7000

### ISSUE THREAD

**Issue by toitoine38** [Lanchon/REPIT#113]
Hi everybody !

I-am trying to upgrade my android version on my note 1 from android 6 to 8. I followed instructions given on the xda-developpers forum where they said than one of the needed steps is to use lanchan to re-partition the system  with dedicated code and syntax.
The one I used for my phone is : 

lanchon-repit-20170115-system=2G+keep-data=5G+keep-sdcard=max+keep-preload=min+wipe-n7000

I also tried : 

lanchon-repit-20170115-system=3G+keep-data=8G+keep-sdcard=max+keep-preload=min+wipe-n7000

and at each time it does not work with error message " the sdcard1 is busy" sdcrd1 is the external sdcrd of my phone
I tried with removing the sdcard part of the code and same problem. I tried to launch the code from the internal memory and same problem "sdcard0 (internal memory) is busy"

Is there an error on my syntax on on the way i use the code ?

Thanks a lot for your help
Antoine

**Comment by Lanchon** [comment]
explained in the docs
