### ISSUE TITLE
Xiaomi Mi 4 (cancro)

### ISSUE THREAD

**Issue by crypto0007** [Lanchon/REPIT#114]
[repit-dump[1].log](https://github.com/Lanchon/REPIT/files/11224883/repit-dump.1.log)
  
MI 4, codename = cancro
twrp-3.7.0_9-0-cancro, official
kernel: 3.4.113-perf-gbb2d2b70f351
ROM: LineageOS 18.1
stock partition layout

**Comment by Lanchon** [comment]
xiaomi mi 4 is snapdragon 801. the partition table is probably signed. see #55
