### ISSUE TITLE
not compatible with arnab's TWRP 3.0.0.0 build (required tool 'parted' missing)

### ISSUE THREAD

**Issue by psuet** [Lanchon/REPIT#13]
I tried to resize my system-partition with the standard parameters and with the recommended IsoRec_TWRP_3.0.0-0 Recovery.

I get the following error:

> FATAL: required tool 'parted' missing (please use a recent version of TWRP to run this package)

How could this be fixed?

**Comment by Lanchon** [comment]
thanks for the repot.

unfortunately TWRP 3 is missing many required tools. for now use isorec TWRP 2.7.8.0 to run the script. i dont know if arnab plans to improve twrp 3 in this regard. either way, i have a plan to make this work on any recovery.

**Comment by Lanchon** [comment]
this should be fixed now that repit bundles a complete runtime environment. if you test, please report.

**Comment by giapoldo** [comment]
Same error. Tested with TWRP 3.0.2-1.

**Comment by Lanchon** [comment]
thank you for the **very complete** bug report!! let me help you...

you are doing something wrong. please do it better.

**Comment by giapoldo** [comment]
No need to be dense, I didn't know what else to inform. In any case, The phone is an i9100 and had CM12.1, pico GApps, TWRP 3.0.2-1. and the TRIM-IsoRec-20160206-cm-12.1-i9100 kernel version.
I flashed IsoRec TWRP 2.8.7-0 afterwards and had to install it from /tmp, since it didn't work straight from external SD. 
What other info do can I provide? I don't know what's useful.

Thank you for your work.

**Comment by Lanchon** [comment]
this has been fixed with a workaround months ago. useful would have been all this info plus, for instance, the version of REPIT you are flashing. i'm sure it's old; old versions are not supported.

and above all, THE LOG! no log. no support; that is clear in the doc section.

**Comment by giapoldo** [comment]
REPIT version is 20160317, which is indeed prior to march 29, when you informed of the bundled environment. Case closed.

Thanks again, and sorry for the trouble.

**Comment by Lanchon** [comment]
glad you got it working!
