### ISSUE TITLE
Had an issue with mmblck09, sorted

### ISSUE THREAD

**Issue by roelvanderplank** [Lanchon/REPIT#14]
Hi, just wanted to post it if others have the same problem:
I wanted to update my phone from CM12.1 to 13.
Installing the script gave the error that mmblck09 (or similar, do not know the exact name) was mounted.
This gave an error in the end. Installing e.g. the CM13 zip was not possible.

Solved in the end by manually unmounting everything. Navigating to the script on my external(!) sdcard made the error come back. Fortunately, the script was ALSO visible on the /tmp folder, and so I could in the end install it while NOT having either the emmc or the external SDcard mounted (not even by default through twrp 2.7.something).

So I was able to fix it in the end (but I was sweating in the meantime though).

Perhaps an option(?) is to have people copy the script to /tmp, then have the script unmount everything including the external SDcard?

Anyways, thanks for your script, have a functioning phone now!

Kind regards,
Roel

**Comment by roelvanderplank** [comment]
Just for the record, my phone is working, so closing it ;-0

**Comment by Lanchon** [comment]
the script copies itself to /tmp when it cant unmount, and then asks you to run it from there. it's also explained in the instructions lol :) anyway, thanks for the report :)
