### ISSUE TITLE
'device-dump' tool not working from windows

### ISSUE THREAD

**Issue by MalcolmMcConnor** [Lanchon/REPIT#15]

**Comment by MalcolmMcConnor** [comment]
Ok, I tried again but it seems my understanding of linux or your tool is insufficient:

I installed minimal ADB Tools. Those recognised my phone also in Recovery but i constantly got authorisation error when running your batch. Enabled USB Debugging in Android - to no avail. In TWRP I could find any cure for this ADB Sideload feature was no help too.

So while in TWRP I copied dump.sh to the /tmp/directory and then issued following command from within TWRP (while in /tmp/):

sh /tmp/dump.sh >dump-out.txt

That created me the text file but this one has only one error message:

dump.sh:line 5: syntax error: unexpected newline

I suspect there must be more to it - perhaps some more files are needed.

I am merely a windows user of my android phone. I am willing to try again but I need a more detailed info on how to do it - I guess other users too. Can you help out, please.

Greetings,

**Comment by Lanchon** [comment]
thanks!

newlines in windows on one hand and linux/unix/macos/rest-of-the-world on the other are different. it looks like your OS converted 'dump.sh' to windows-style newlines and then the shell in your phone found unexpected characters.

two things you can try:

1) make it work as it is:
- git clone my repo to your PC. (if you cloned it before, pull the latest changes!)
- verify that the dump.sh file has un*x-style newlines:
  - open it with notepad and it should all look like a very long mess of a line.
- verify that you can access recovery via adb:
  - assumption: your windows setup works for adb into android.
  - boot into recovery and then run `adb devices` on the PC:
    - it should list the device as 'recovery'.
    - if not listed, you probably need windows drivers for adb to recovery (windows is a bitch).
    - if listed as 'unauthorized', your probably need to run the adb client daemon with administrator privileges:
      - open a new command prompt window with admin privs.
      - run `adb kill-server`.
      - run `adb devices` again to check that the device status changed to 'recovery'.
- finally execute 'run-dump.bat' on the PC; it should create 'dump-out.txt'.

2) i can make a zip file for you to flash in recovery instead. you'd still need to pull the recovery log to get the output of the script.

**Comment by Lanchon** [comment]
here is a recovery flashable version:
[flashized-device-dump.zip](https://github.com/Lanchon/REPIT/files/176996/flashized-device-dump.zip)

after flashing, the output will be within TWRP's log. you need to somehow get the 'recovery.log' file:
http://rootzwiki.com/topic/24120-how-to-get-a-log-from-twrp/

**Comment by Lanchon** [comment]
closing: user chose to run flashable version.
