### ISSUE TITLE
Port Request to i9100G

### ISSUE THREAD

**Issue by MalcolmMcConnor** [Lanchon/REPIT#16]
Hello Lanchon,

Thanks for your in-depth description of how to obtain a log under windows.

As promising as it seemed to get the adb connection working at the moment I just didnt have the time to do it; so I went with option 2) (flashable dump tool) that seems to have worked very fine - thanks for this invaluable option.

I tried to attach the log file renamed as txt and also packed to a zip but github kept insisting I should "try again" - so here is the link to the file on my dropbox:

https://dl.dropboxusercontent.com/u/1500968/recovery.log

Thanks again for making this happen.

**Comment by MalcolmMcConnor** [comment]
I should add the probably important fact that I repartitioned the phone via pit file to accomodate lollipop needs (/data to 4 GB). So the log-file does not reflect factory settings...

**Comment by Lanchon** [comment]
on the contrary, thank you!!
done: https://github.com/Lanchon/REPIT/commit/b2d8f73b3cfc8a2a9e5e3be51ff3ea075e24b3cc
will push a new release for you soon.

**Comment by Lanchon** [comment]
i forgot to mention that you are in luck because your recovery supports all required operations :)

**Comment by Lanchon** [comment]
done!
https://github.com/Lanchon/REPIT/releases/tag/2016-03-17
https://www.androidfilehost.com/?w=files&flid=52298

**Comment by MalcolmMcConnor** [comment]
Wha.... Done? Man, you are coding like crazy! I will now dig into your guide on how to rename for me to utilize all of the unused preload space and leave all the rest untouched for the time beeing. If data is preservable during this procedure all the better. If not I can restore a nandroid after resizing...

Now I will have to find another "issue" to be notified of updates...

Thanks again from Stuttgart, Germany

**Comment by Lanchon** [comment]
:) yes, data will be preserved unless you wipe.

use `lanchon-repit-20160317-sdcard=max-preload=min+wipe-i9100g.zip` to wipe preload, shrink it, and donate its former space to internal sdcard.

resizing data and sdcard are 'cheap' operations, and the more free space in them the cheaper. resizing system is expensive, as all of /data must be moved (even the free area of the /data partition).

if you have a REALLY BIG /data partition with a lot of free space in it, and you want to resize /system:
- shrink /data and resize /system in a single REPIT (it's clever enough to order stuff by itself).
- then expand /data again with a second REPIT run.

**Comment by Lanchon** [comment]
credit: https://github.com/Lanchon/REPIT/commit/0c0bb7b95e05da0716408bec92eca5bd1bee0408

thanks!

**Comment by opvosis** [comment]
how to flash this? 
https://github.com/Lanchon

**Comment by Lanchon** [comment]
please don't spam issues!
well, read the docs, it's there.
i just created an xda thread for user discussion, if you are too lazy to read:
http://forum.xda-developers.com/android/software-hacking/tool-lanchon-repit-data-sparing-t3358036
