### ISSUE TITLE
Failed to sysmapfile

### ISSUE THREAD

**Issue by MaxPower87** [Lanchon/REPIT#21]
I always get errormessage:
Failed to sysMAPFile "/file/path"
Nothing else in the logs....

Do you know this error? Google doesnt know the answer 😞

**Comment by Lanchon** [comment]
what exact device? what exact recovery?

**Comment by MaxPower87** [comment]
Its a samsung galaxy s2 i9100 with TWRP v2.8.7.0
cm13 is already running, but i have to repartition due to GApps installation.
executing repit from internal and external sdcard shows the same error

**Comment by Lanchon** [comment]
exactly which TWRP? my file?
kernel? a recent CM13 official nightly?
and i need the logfile
