### ISSUE TITLE
Dumpfile maguro i9250

### ISSUE THREAD

**Issue by ghost** [Lanchon/REPIT#25]
As requested here the recovery log obtained on unofficial twrp 3.0 on my i9250. 

[recovery.txt](https://github.com/Lanchon/REPIT/files/201273/recovery.txt)

Im open to further testing of course, pls let me know if you need sth. else.
Thanks !

**Comment by Lanchon** [comment]
thanks so much!

done, here:
https://www.androidfilehost.com/?fid=24459283995312549

the default setting will shrink cache to 62 MiB and expand system to 1024 MiB (1 GiB).
please note that resizing /data (without wipe) on this is VERY INEFFICIENT, and can easily take an hour of work, even if /data is mostly empty.

please test and get back, thanks again!

**Comment by ghost** [comment]
Hi Lanchon,

tried as requested and got this :

############################

Installing zip file '/sdcard/lanchon-repit-20160404-system=1.0-cache=0.0605+wipe-data=same-maguro.zip'
Checking for MD5 file...
Skipping MD5 check: no MD5 file found
I:Zip does not contain SELinux file_contexts file in its root.
I:Legacy property environment initialized.

Illegal instruction

[ERROR 132]

Updater process ended with ERROR: 132
I:Legacy property environment disabled.
Error installing zip file '/sdcard/lanchon-repit-20160404-system=1.0-cache=0.0605+wipe-data=same-maguro.zip'
Updating partition details...
I:Data backup size is 0MB, free: 11192MB.
I:Unable to mount '/usb-otg'
I:Actual block device: '', current file system: 'vfat'
...done
I:Set page: 'flash_done'
I:operation_end - status=1
I:Set page: 'clear_vars'
I:Set page: 'install'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'advanced'
I:Set page: 'filemanagerlist'
I:Set page: 'filemanageroptions'
I:Set page: 'choosedestinationfolder'
I:Set page: 'filemanagerconfirm'
I:Set page: 'filemanageraction'
I:operation_start: 'Command'
I:Running command: 'cp "/tmp/recovery.log" "/sdcard"'

####################################

thought it might be recovery related but same happens with latest official 2.8.7.0 twrp and unofficial 3.0 twrp. 

Thanks !

**Comment by Lanchon** [comment]
new release should fix this issue!!!
https://www.androidfilehost.com/?w=files&flid=53660
