### ISSUE TITLE
Tool Failing

### ISSUE THREAD

**Issue by viglaman** [Lanchon/REPIT#26]
Hello! I hope you are well. I am running TWRP 2.8.7.0 and I also tried with 3.0.0.0 and the same thing happens. The zip file fails to install. I copy to /tmp, unmount all filesystems but still the same happens. It fails without any obvious reason why.

Thank you for your help!

**Comment by Lanchon** [comment]
hi,
please provide:
-log
-kernel info
-recovery info (which recovery, not the version)
thanks!

**Comment by viglaman** [comment]
Hello,

The device is Galaxy S2 with CyanogenMod 13.0-20160404-NIGHTLY-i9100 with kernel 3.0.101-CM-g3419d2. The recovery is TWRP version 2.8.7.0 Isorec and I am attaching the log.

[recovery.txt](https://github.com/Lanchon/REPIT/files/205438/recovery.txt)

**Comment by Lanchon** [comment]
thanks. it's very strange, the log only shows:

```
Installing '/tmp/lanchon-repit-20160328-system=1+keep+ext4-data=same+keep+ext4-sdcard=max+keep+vfat-preload=min+wipe-i9100.zip'...
Checking for MD5 file...
Skipping MD5 check: no MD5 file found
Error flashing zip '/tmp/lanchon-repit-20160328-system=1+keep+ext4-data=same+keep+ext4-sdcard=max+keep+vfat-preload=min+wipe-i9100.zip'
```

no text, not even an error code! could it be a bad download of the zip? can you extract it?

**Comment by Lanchon** [comment]
please try the new release, it might fix this:
https://www.androidfilehost.com/?w=files&flid=53660

**Comment by viglaman** [comment]
Let me try that and come back to you!

**Comment by viglaman** [comment]
It worked perfectly! Thank you very much!

**Comment by Lanchon** [comment]
thanks!
