### ISSUE TITLE
unified storage?

### ISSUE THREAD

**Issue by kiradotee** [Lanchon/REPIT#27]
Hi,
Hence the thread has been moved from xda to github I'm posting this here.

Is it possible to unify the storage on i9100? As currently I have around 2GB internal storage and the rest 10+GB appears as an SD card. Thanks.

**Comment by Lanchon** [comment]
yes it is, but this hasn't been done yet. i mean to look into it but i don't think i have the time. also, it is not without some peril.

for now, if you are using CM, may i suggest you repit with this config:
-system=1-data=6-sdcard=max-preload=min+wipe
(from project docs)

1GB system, 6GB data, no preload, the reminder gets to be internal sdcard.
you need to have at least about 7GB free in internal sdcard.

read the docs before continuing!
