### ISSUE TITLE
Fails to resize SYSTEM partition

### ISSUE THREAD

**Issue by camp0s** [Lanchon/REPIT#3]
I was executing -system=0.6+keep-data=2.3+keep-sdcard=max+keep-preload=min+keep but after 10 minutes the process aborted and nothing was done.

The only change is to SYTEM actually at 0.5Gb to 0.6Gb for more space

Where do I find the LOGs to paste here?

**Comment by Lanchon** [comment]
i seriously doubt that after 10 minutes nothing was done.

you were also sizing data. next time use data=same or data= or simply don't define data.

DO NOT RESIZE YOUR PARTITIONS ALL THE TIME, unless you are wiping: IT CAUSES WEAR to the emmc to move stuff around. do not resize and keep your partitions nearly full: file systems are not designed to run full. do not resize /system often, as you have to move all of /data each time to do it. use system=1 instead. absolutely NEVER use the phone with /data near full. /data is the only trimmable partition and should have 2 or at the very least 1 GB FREE ALL THE TIME. your choice of data=2.3 is extremely suspect. use data=6 instead. delete unneeded stuff from internal sdcard. your phone needs the internal storage TO FUNCTION, not to carry your stuff around. add an sdcard if you want movies of music or whatever.

finally please never ask stuff that you can google!!!!!
http://lmgtfy.com/?q=twrp+log
`adb pull /tmp/recovery.log`

**Comment by Lanchon** [comment]
i'm closing this issue due to no log.
but feel free to add comments and i'll reopen if needed.
thanks!

**Comment by camp0s** [comment]
So fast! let me recap.

I was on slimsaber 4.4.4 with original partitioning 0.5/2/sdcard/preload. I upgraded to CM 12.1 + pico_gapp, after that I reduced preload and nothing more, it worked the first time (that was after the wipe before flashing everything).

I'm restoring the phone and noticed that /system had 33Mb free, and data was around 400MB free. I just tuned the script to give a little more /system (after busybox I'm not installing other things there) and a little more data to have almost 1Gb free.

I'm not using games or other data app (not even Nav app) and I often swap the sdcard, so it's not safe for me to use as primary storage.

Can't find any recovery.log on the whole phone (starting from /).

I'll execute this:
lanchon-repit-20160225-system=0.7+keep-data=same-sdcard=max+keep-preload=min+keep.zip

..and take a _dumb_ photo of the screen if the error comes again.

**Comment by Lanchon** [comment]
you have to pull the recovery.log **after flashing and before leaving TWRP**. as you can see, it's in /tmp, a.k.a RAM; you wont find it on any real disk.

always better wipe if you don't care about the contents:
-preload=min+wipe

my recommendation for sizes remain: for 300MB it's not worth the trouble the next time you need to upgrade your phone and it doesnt fit. **empty space is not wasted** if you trim it, on /system and /data. **EMPTY SPACE IS A COMPLETE WASTE ON SDCARD** unless your sdcard is ext4 formatted. i suggest 1GB sys 4GB data, minimum, and then trim at least once.

**Comment by Lanchon** [comment]
about the closing: i really can't help you without a log.

**Comment by camp0s** [comment]
Sorrrry! I had a directory on the root called /tmp >.<

I'm running your script now..

I can't access anymore the device via ADB from recovery (TWRP 2.8.7.0) but it works when the phone is fully booted in the rom.

**Comment by camp0s** [comment]
**I have it, finally!**

```
Installing '/sdcard/lanchon-repit-20160225-system=0.7+keep-data=same-sdcard=max+keep-preload=min+keep.zip'...
Checking for MD5 file...
Skipping MD5 check: no MD5 file found
I:Zip does not contain SELinux file_contexts file in its root.
I:Legacy property environment initialized.

 ####################################
  Lanchon REPIT
  A Data-Sparing Repartitioning Tool
  Version: 2016-02-25
  Device: i9100
  Copyright 2016, Lanchon (GPLv3)
 ####################################

=====  PRELIMINARY CHECKS  =====
info: valid package name: <prefix>[-system=<conf>][-data=<conf>][-sdcard=<conf>][-preload=<conf>]<suffix>
info: valid partition configuration: [<size-in-GiB>|same|min|max][+[keep|wipe][+[ext4|vfat]]]
info: partition configuration defaults: system|data|preload=same+keep+ext4 sdcard=same+keep+vfat
info: parsing package name

-----  CONFIGURATION  -----
system: size=0.7, content=keep, fs=ext4
data: size=same, content=keep, fs=ext4
sdcard: size=max, content=keep, fs=vfat
preload: size=min, content=keep, fs=ext4

info: copying package to /tmp
info: unmounting all partitions
info: rereading partition table

=====  PREPARATION  =====
info: unmounting all partitions
info: rereading partition table
info: detecting eMMC size
info: eMMC size is 16 GB
info: checking existing partition layout
info: current size: partition #9 /system (FACTORYFS): 512 MiB
info: current size: partition #10 /data (DATAFS): 2355 MiB
WARNING: unallocated space between partition #9 /system (FACTORYFS) and partition #10 /data (DATAFS)
info: current size: partition #11 /sdcard (UMS): 11776 MiB
info: current size: partition #12 /preload (HIDDEN): 8 MiB
info: checking new partition layout
info: new size: partition #9 /system (FACTORYFS): 717 MiB
info: new size: partition #10 /data (DATAFS): 2355 MiB
info: new size: partition #11 /sdcard (UMS): 11776 MiB
info: new size: partition #12 /preload (HIDDEN): 8 MiB

=====  DRY-RUN  =====
-----  analyzing partition #9 /system (FACTORYFS)
*****  processing partition #9 /system (FACTORYFS)
info: will resize the ext4 partition
info: checking and trimming the file system
/dev/block/mmcblk0p9: 2072/32768 files (0.0% non-contiguous), 122390/131072 blocks
-----  analyzing partition #10 /data (DATAFS)
*****  processing partition #10 /data (DATAFS)
info: will enlarge the ext4 file system if needed to fill its partition
info: checking and trimming the file system
/dev/block/mmcblk0p10: 4472/155648 files (7.1% non-contiguous), 443983/602880 blocks
-----  analyzing partition #11 /sdcard (UMS)
*****  processing partition #11 /sdcard (UMS)
info: checking the file system
dosfsck 3.0.12, 29 Oct 2011, FAT32, LFN
Starting check/repair pass.
Starting verification pass.
/dev/block/mmcblk0p11: 512 files, 2803/1505853 clusters
-----  analyzing partition #12 /preload (HIDDEN)
*****  processing partition #12 /preload (HIDDEN)
info: will enlarge the ext4 file system if needed to fill its partition
info: checking and trimming the file system
/dev/block/mmcblk0p12: 17/512 files (11.8% non-contiguous), 2008/2048 blocks

=====  EXECUTION  =====
-----  analyzing partition #9 /system (FACTORYFS)
*****  processing partition #9 /system (FACTORYFS)
info: enlarging the partition entry
info: deleting current partition
Warning: Not all of the space available to /dev/block/mmcblk0 appears to be used, you can fix the GPT to use all of the space (an extra 2048 blocks) or continue with the current setting? 
Error: Partition /dev/block/mmcblk0p9 is being used. You must unmount it before you modify it with Parted.

[ERROR 1]

I:Legacy property environment disabled.
E:Error executing updater binary in zip '/sdcard/lanchon-repit-20160225-system=0.7+keep-data=same-sdcard=max+keep-preload=min+keep.zip'
Error flashing zip '/sdcard/lanchon-repit-20160225-system=0.7+keep-data=same-sdcard=max+keep-preload=min+keep.zip'
Updating partition details...
I:mount -o bind '/emmc/.android_secure' '/and-sec' process ended with RC=0
...done
I:Set page: 'flash_done'
I:operation_end - status=1
I:Set page: 'clear_vars'
I:Set page: 'install'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'backup'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'advanced'
I:Set page: 'confirm_action'
I:Set page: 'action_page'
I:operation_start: 'Copy Log'
I:Copying file /tmp/recovery.log to /sdcard/recovery.log
```

**Comment by Lanchon** [comment]
are you using the latest isorec TWRP i publish?

if yes, unmount everything then try this:
adb shell cat /proc/mounts
and paste the result, thanks.

EDIT: of course run this while running TWRP.

**Comment by camp0s** [comment]
TWRP: I'm using this file "recovery-Lanchon-IsoRec-TWRP-2.8.7.0-20160113-i9100-(by-arnab).zip" as instructed.

After getting in recovry I used the terminal on TWRD to issue the command "cat /proc/mounts", then copied the log to SD:

```
# cat /proc/mounts
I:Actual command is: 'cd "/" && cat /proc/mounts 2>&1'
rootfs / rootfs rw,noatime,nodiratime,size=406696k,nr_inodes=101674 0 0
tmpfs /dev tmpfs rw,nosuid,noatime,nodiratime,mode=755 0 0
devpts /dev/pts devpts rw,noatime,nodiratime,mode=600 0 0
proc /proc proc rw,noatime,nodiratime 0 0
sysfs /sys sysfs rw,noatime,nodiratime 0 0
tmpfs /tmp tmpfs rw,noatime,nodiratime 0 0
/dev/block/mmcblk0p7 /cache ext4 rw,noatime,nodiratime,data=ordered 0 0
/dev/block/mmcblk0p11 /emmc vfat rw,noatime,nodiratime,fmask=0000,dmask=0000,allow_utime=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro 0 0
/dev/block/mmcblk0p11 /and-sec vfat rw,noatime,nodiratime,fmask=0000,dmask=0000,allow_utime=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro 0 0
/dev/block/mmcblk1p1 /sdcard vfat rw,noatime,nodiratime,fmask=0000,dmask=0000,allow_utime=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro 0 0
I:Set page: 'terminalfolder'
I:Set page: 'advanced'
I:Set page: 'confirm_action'
I:Set page: 'action_page'
I:operation_start: 'Copy Log'
I:Copying file /tmp/recovery.log to /sdcard/recovery.log
```

About the "unmount everything" is something automatic mounted in TWRP?

As a side note, I lost adb access when the phone is in recovery ("adb devices" reports nothing) - but I can perform "adb reboot recovery" in standard mode.

**Comment by Lanchon** [comment]
by unmount everything i mean going to TWRP's mount menu and manually unmounting everything.

i really don't know why parted reports your /system partition being locked. it doesn't show up as mounted or anything, very strange.

regarding recovery ADB: my setup requires root to run the adb daemon for it to connect to adbd on recovery. in my linux box this entails killing the current server if running `sudo adb kill-server` and starting it up again under root `sudo adb devices`. (however, when it can't connect the phone still shows up; i think it shows up as 'unauthorized' or something similar.) i don't know how things work on windows.

**Comment by camp0s** [comment]
Does this message mean anything?

`WARNING: unallocated space between partition #9 /system (FACTORYFS) and partition #10 /data (DATAFS)`

I was reading here:

```
info: current size: partition #9 /system (FACTORYFS): 512 MiB
info: current size: partition #10 /data (DATAFS): 2355 MiB
info: current size: partition #11 /sdcard (UMS): 11776 MiB
info: current size: partition #12 /preload (HIDDEN): 8 MiB
info: checking new partition layout
info: new size: partition #9 /system (FACTORYFS): 717 MiB
info: new size: partition #10 /data (DATAFS): 2355 MiB
info: new size: partition #11 /sdcard (UMS): 11776 MiB
info: new size: partition #12 /preload (HIDDEN): 8 MiB
```

About sizes, shouldn't SDCARD becomes around 11576MiB rather than 11776MiB? because I enlarged the SYSTEM by 200MiB.

**Comment by Lanchon** [comment]
everything is the way it should. the unallocated space was made by repit (those 10 minutes) to make space for growing system.

the only trouble is that system cant be modified because it is locked.

**Comment by camp0s** [comment]
If I were to use `wipe`option in your script, would that trigger a more aggressive handling? (rather than resize, remove and recreate from blank).

**Comment by Lanchon** [comment]
you can try. but i guess it will fail with the exact same error.

**Comment by camp0s** [comment]
I was reading the script:

```
ROW.201 size=$(awk "BEGIN {print int(($size) * $unit + 0.5)}")
ROW.202 size=$(( ($size) * $granularity ))
```

So I set `size=0.55`, I get 0.55x1024 + 0.5 = 563.7 then 563.7x2048 = 1154457.6

How is going to be used, is it comma safe for the rest of the script?

**Comment by Lanchon** [comment]
there is no fractional part: partition sizes are rounded to the nearest MiB as documented (unless `same` is used). what are you trying to achieve? the problem with your phone is that parted thinks the partition is locked. something is locking it, that's all. we don't know what.

**Comment by camp0s** [comment]
I was just reading the script, however I got this log (again from windows, via recovery with parted):

```
Model: MMC VYL00M (sd/mmc)
Disk /dev/block/mmcblk0: 15.8GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt

Number  Start   End     Size    File system  Name       Flags
 1      4194kB  25.2MB  21.0MB  ext4         EFS
 2      25.2MB  26.5MB  1311kB               SBL1
 3      27.3MB  28.6MB  1311kB               SBL2
 4      29.4MB  37.7MB  8389kB               PARAM
 5      37.7MB  46.1MB  8389kB               KERNEL
 6      46.1MB  54.5MB  8389kB               RECOVERY
 7      54.5MB  159MB   105MB   ext4         CACHE
 8      159MB   176MB   16.8MB               MODEM
 9      176MB   713MB   537MB   ext4         FACTORYFS
10      928MB   3397MB  2469MB  ext4         DATAFS
11      3397MB  15.7GB  12.3GB  fat32        UMS        msftres
12      15.7GB  15.8GB  8389kB  ext4         HIDDEN
```

Des it help? I need back access but via recovery..

**Comment by Lanchon** [comment]
not really. we need to find whats locking your partition. what kernel are you using?

**Comment by camp0s** [comment]
I'm using Dorimanx LP V11.0b031 (20 feb).

This evening I flashed a new PIT via ODIN with an enlarged SYSTEM, after that I used your script to resize DATA, reduce PRELOAD and fill the rest with SDCARD. It worked, as long as I didn't touch SYSTEM.

From the LOGs, could you deduce at which point the script hangs? Row 579 it executes "processParRecreate $n $newStart $oldSize $newStart $newSize".

Would be ok to insert a umount just before the command at row 379 to forcefully unmont the partition we are going to delete? whatever it is the script decided to delete, just do it with a strong kick :)

**Comment by Lanchon** [comment]
nope. the partition is already unmounted. the script refuses to start if any part of the emmc is mounted and it can't unmount it.

also, if **any** partition is mounted, then the partition table cannot be reread, which is a requirement for starting the script. in your case the script starts because the PT can be reread; which is incompatible with the notion of any partition being locked. it almost seems like some kind of bug of the locking system. maybe the kernel?

**Comment by manquetin** [comment]
Adding my 2 cents.

I have exactly the same problem. I wanted to enlarge system from 1GiB to 2GiB, but the script fails with mmcblk0p9 being mounted, even if /proc/mounts does not show anything.
Trying to run the script manually, I saw that the error message was sent by 'parted' while trying to delete system partition.

FYI, I was running stock CM12.1 kernel and IsoRec-TWRP-2.8.7.0. I also tried with TWRP-3.0.0 but ATM, it misses 'parted' as well as other utilities so the script can't be run.

**Comment by Lanchon** [comment]
hi! somebody reported that having the external sdcard mounted made the kernel unable to unmount /system somehow.

could you please try:
- rebooting to twrp 2.8.7.0, then _not_ mounting anything via USB to the PC.
- run script once (will copy itself to /tmp).
- manually unmount everything using twrp's menu, including external SD card. (you could also boot twrp without the card in place.)
- run script again from /tmp.

thanks!

**Comment by niccoloo** [comment]
Hi!
I had exactly the same problem.
Running the script a second time from /tmp after unmounting everything fixed it.
Thanks!

**Comment by Lanchon** [comment]
the script now unmounts the sdcard by itself: https://github.com/Lanchon/REPIT/commit/fa82f4596fef5dad7bd84bf5773d3c29fa969cf3
hopefully this will fix this issue, closing, thanks!
