### ISSUE TITLE
Update handling of partition size parameters

### ISSUE THREAD

**Issue by Lanchon** [Lanchon/REPIT#30]
- eliminate per-device configurability of size unit.
- make GiB the default size unit.
- accept G and M suffixes to explicit sizes.
- change default filenames to use M (and maybe G too).

**Comment by bigmadgeek** [comment]
Hi there,
about 2 months ago i was using your tool to repartition my i9100, 
btw. good job with this tool, i have broken micro usb port and can't connect it with the computer so i was big help for me
back then i used ** lanchon-repit-v0.1-sys1GB-i9100.zip**
but this is too small sys partition for me, there was different files for different sys sizes, i just need to make my sys partition 2gb, but i donk't know how to name the file or how big rest of partitions might be ;/

**Comment by Lanchon** [comment]
please don't spam unrelated issues!!!

**Comment by bigmadgeek** [comment]
sorry, just couldn't posted on xda due post limitations - i'll delete those spam then ;]

**Comment by Lanchon** [comment]
bigmadgeek, i can't message you on github becuase of your settings and i can't find you on XDA.

sorry i was unaware that you couldn't post on XDA. if you still get this message, please create a NEW issue here.

your original message was:

> Hi there,
> about 2 months ago i was using your tool to repartition my i9100,
> btw. good job with this tool, i have broken micro usb port and can't connect it with the computer so i was big help for me
> back then i used *\* lanchon-repit-v0.1-sys1GB-i9100.zip**
> but this is too small sys partition for me, there was different files for different sys sizes, i just need to make my sys partition 2gb, but i donk't know how to name the file or how big rest of partitions might be ;/

**Comment by Lanchon** [comment]
done. (the use of units is forced rather than optional.)
