### ISSUE TITLE
Port request for j5lte (Samsung Galaxy J500F Duos)

### ISSUE THREAD

**Issue by aintnobodygottimeforthat** [Lanchon/REPIT#39]
Hi Lanchon, 
this is a port request for one of the variants of the Samsung Galaxy J5.
- 'repit-dump.log' file atttached

file attached and also here http://pastebin.com/7yFv2553
- your exact device and device codename.

Samsung Galaxy SM-J500F/DS codename j5lte
- your recovery (version? official? if not where did you get it?).

TWRP 3.0.2.0 unofficial by Nick Verse http://forum.xda-developers.com/android/development/recovery-samsung-galaxy-j5-t3338869
- your kernel

CM kernel see below
- your rom

CM12.1 unofficial by Nick Verse 
[repit-dump.log.txt](https://github.com/Lanchon/REPIT/files/345317/repit-dump.log.txt)
http://forum.xda-developers.com/android/development/rom-cyanogenmod-samsung-galaxy-j5-t3404569
I am running the 20160621 version from here https://www.androidfilehost.com/?w=files&flid=55526
- is your device running the stock partition layout or is it already modified?

stock (LP) layout
- other

please note that the J5 comes in myriad of variants (SM-J500F / SM-J500FN / SM-J500H / SM-J500M / SM-J50007 / SM-J500G / SM-J50008 / SM-J500Y) which may or may not differ in partition layouts.
Should you want to postpone this request until we gather the relevant logs for all the variants, I am happy to accept this and gather the logs.

Regards
ajislav 
(ex i9100 user)
[repit-dump.log.txt](https://github.com/Lanchon/REPIT/files/345315/repit-dump.log.txt)

**Comment by Lanchon** [comment]
hey ajislav! thanks for the request.

so everything looks fine for this. what is the rationale? reducing system for a bigger userdata?

if you'd like to help with the variants problem, maybe you could google some partition dumps of other variants in online forums and post anything you can find. running the dump on variants is not really necessary (unless they are different and someone wants a port).

**Comment by Lanchon** [comment]
j5lte is the codename specifically of the J500F? or does it apply to the whole J5 family?

**Comment by aintnobodygottimeforthat** [comment]
Hello Lanchon, yes, bigger user data is the goal (I know it's not much, but for some it could make a difference). I'll get back to you regarding the codenames and partition layouts in a few days (am on holiday now) as I think it makes sense to do it once for the whole J5 family and not per partes

**Comment by Lanchon** [comment]
since you are on vacation, and soon i'll be off too, i think i better proceed with what i have.

but could you please answer this?

> j5lte is the codename specifically of the J500F? or does it apply to the whole J5 family?

**Comment by aintnobodygottimeforthat** [comment]
Yes this is only for J500F

**Comment by Lanchon** [comment]
hi ajislav,

i'm very sorry about making no progress on this. i'm on vacation... :(

**Comment by aintnobodygottimeforthat** [comment]
Hello Lanchon,
No worries, enjoy your vacation.
It seems we may not need a repit after all as the GPT seems to be locked (needs to be confirmed). Hence, I would like to pause this issue  for now. I will let you know either way once I know for sure.
Ajislav

**Comment by Lanchon** [comment]
what makes you say that?

**Comment by Lanchon** [comment]
done

**Comment by ghost** [comment]
Please could I make a partition for the

J5LTE Models:
- SM-J500F
- SM-J500G
- SM-J500M
- SM-J500NO
- SM-J500Y

**Comment by mtbcoin** [comment]
Will REPIT work on this device? Trying it in stock Android 6.0.1.

Installed busybox to /tmp/xbin and added to script.sh:
```bash
export PATH="/tmp/xbin:$PATH"
PATH="/tmp/xbin:$PATH"
```

When running REPIT from TWRP:
```
umount: can't umount /sdcard1: Resource busy
```
So I install it via adb shell:
```
j5nlte:/tmp # twrp install /tmp/lanchon-repit-20211130-system\=1.5G-cache\=same+wipe-hidden\=min-data\=max-j5nlte.zip

Installing zip file '/tmp/lanchon-repit-20211130-system=1.5G-cache=same+wipe-hidden=min-data=max-j5nlte.zip'
Checking for Digest file...
Unmounting System...

 ####################################
  Lanchon REPIT
  A Data-Sparing Repartitioning Tool
  Version: 2017-01-15
  Device: j5nlte
  Copyright 2016, Lanchon (GPLv3)
 ####################################

=====  PRELIMINARY CHECKS  =====
info: valid package names: <prefix>[-(system|cache|preload|data)=<conf>]...<suffix>
info: valid partition <conf> values: [<size>(G|M)|same|min|max][+[keep|wipe][+[ext4|vfat|f2fs|swap|raw]]]

-----  DEFAULTS  -----
system = size:same + content:keep + fs:ext4
cache = size:same + content:keep + fs:ext4
preload = size:same + content:keep + fs:ext4
data = size:same + content:keep + fs:ext4

info: parsing package name

-----  CONFIGURATION  -----
system = size:1.5G + content:keep + fs:ext4
cache = size:same + content:wipe + fs:ext4
preload = size:same + content:keep + fs:ext4
data = size:max + content:keep + fs:ext4

info: disabling swap
info: unmounting all partitions
info: rereading partition table

=====  PREPARATION  =====
info: determining usable sector range of block device
Warning! Main and backup partition tables differ! Use the 'c' and 'e' options
on the recovery & transformation menu to examine the two tables.

Warning! One or more CRCs don't match. You should repair the disk!

info: checking existing partitions
#####  processing heap 'main'
info: checking existing partition layout
info: current size: partition #25 'system' (system): 2080 MiB
info: current size: partition #26 'cache' (cache): 200 MiB
info: current size: partition #27 'preload' (hidden): 70 MiB
info: current size: partition #28 'data' (userdata): 4913 MiB
info: checking new partition layout
info: new size: partition #25 'system' (system): 1536 MiB
info: new size: partition #26 'cache' (cache): 200 MiB
info: new size: partition #27 'preload' (hidden): 70 MiB
info: new size: partition #28 'data' (userdata): 5457 MiB

=====  DRY-RUN  =====
#####  processing heap 'main'
/tmp/updater: env/script[1630]: ${@: 2}: bad substitution

[ERROR 1]

Updater process ended with ERROR: 1
Error installing zip file '/tmp/lanchon-repit-20211130-system=1.5G-cache=same+wipe-hidden=min-data=max-j5nlte.zip'
Done processing script file
```
Busybox version
```
j5nlte:/tmp/xbin # ./busybox --help
BusyBox v1.31.0 (2019-06-10 15:54:50 CEST) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.
```
However, I tried to repartition drive with **parted** from XDA thread and **parted** from REPIT package. In both cases partition table remained unchanged. So it seems GPT is locked and must be changed by uploading PIT file via Odin?
```
parted /dev/block/mmcblk0

(parted) unit s
(parted) print free

Model: MMC H8G4u! (sd/mmc)
Disk /dev/block/mmcblk0: 15269888s
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags:
 
Number  Start      End        Size       File system  Name        Flags
        34s        8191s      8158s      Free Space
 1      8192s      38911s     30720s                  apnhlos     msftdata
 2      38912s     156543s    117632s                 modem       msftdata
 3      156544s    157567s    1024s                   sbl1
 4      157568s    157631s    64s                     ddr
 5      157632s    161727s    4096s                   aboot
 6      161728s    162751s    1024s                   rpm
 7      162752s    163775s    1024s                   qsee
 8      163776s    164799s    1024s                   qhee
 9      164800s    170943s    6144s                   fsg
10      170944s    170975s    32s                     sec
11      170976s    192511s    21536s                  pad         msftdata
12      192512s    212991s    20480s                  param
13      212992s    241663s    28672s     ext4         efs
14      241664s    247807s    6144s                   modemst1
15      247808s    253951s    6144s                   modemst2
16      253952s    280575s    26624s                  boot
17      280576s    311295s    30720s                  recovery
18      311296s    336897s    25602s                  fota
19      336898s    351215s    14318s                  backup      legacy_boot
20      351216s    357359s    6144s                   fsc
21      357360s    357375s    16s                     ssd
22      357376s    373759s    16384s     ext4         persist
23      373760s    374783s    1024s                   persistent
24      374784s    393215s    18432s     ext4         persdata
25      393216s    4653055s   4259840s   ext4         system
26      4653056s   5062655s   409600s    ext4         cache
27      5062656s   5206015s   143360s    ext4         hidden
28      5206016s   15269847s  10063832s  ext4         userdata
        15269848s  15269854s  7s         Free Space

(parted) rm 28
(parted) rm 27
(parted) rm 26
(parted) resizepart 25 3186687
 
(parted) mkpart physical ext4 3186688 3596287
(parted) name 26 cache
 
(parted) mkpart physical ext4 3596288 3602431
(parted) name 27 hidden
 
(parted) mkpart physical ext4 3602432 15269847
(parted) name 28 userdata
 
(parted) quit

sync
blockdev --flushbufs /dev/block/mmcblk0
partprobe

parted /dev/block/mmcblk0 print free
```
And no partition changed.
