### ISSUE TITLE
GT-I9105P / Galaxsy S2 Plus

### ISSUE THREAD

**Issue by dragoscirjan** [Lanchon/REPIT#41]
Hello there, sorry for bothering, but I'm looking for an advice.

I9105P is the older brother of I9100. It is actually Galaxsy S2 Plus, with a limit of 8GB memory.

I have tried running repit in multiple ways, not worked, all with the same error.

Last I tried looks like `lanchon-repit-20160415-system=2.0-data=3.0-sdcard=max-preload=min+wipe-i9100.zip`.

Error I get always is:

```
flashize-ext: unable to extract package contents

[ERROR 1]
```

Any ideas  ?

**Comment by Lanchon** [comment]
that error means there is something wrong with your TWRP version.

besides that, the i9105P is unsupported.

**Comment by Lanchon** [comment]
closed due to no follow up.
