### ISSUE TITLE
Error installing zip file

### ISSUE THREAD

**Issue by Slamraptor** [Lanchon/REPIT#42]
![screenshot_2016-07-16-22-25-51](https://cloud.githubusercontent.com/assets/20494231/16896994/67eaa382-4ba4-11e6-84e4-8ecc12155dbf.png)

Phone: Samsung Galaxy S2 i9100
Same error with the following Software in all combinations:
TRWP: 2.8.7.0 / 3.0.2.1
OS: TRIM-IsoRec cm-12.1-i9100 / Isorec-TWRP2.8.7.0 12.1 / CM 13 / CM12.1
Repit Version: 2016-04-15

I feel like I missed something on the way while reading tons of pages how to use REPIT but I'm really at the end of my abilities here and hope you can help.

I see that I can't even get into the process of the script but I have absolutely no idea why.

I started out with CM 10.2 and worked my way through all of the above mentioned ROMs and Recoverys tried different filenames and whatnot. I also tried several solutions for mount issues but I think this is an entirely different problem.

Sorry for wasting your time.

**Comment by Lanchon** [comment]
thanks for the detailed report! so... i suspect a bad download. can you check that or upload the file here?

**Comment by Slamraptor** [comment]
[REPIT-2016-04-15_copied_to_phone_and_back.zip](https://github.com/Lanchon/REPIT/files/367620/REPIT-2016-04-15_copied_to_phone_and_back.zip)
[REPIT-2016-04-15_Original Download.zip](https://github.com/Lanchon/REPIT/files/367619/REPIT-2016-04-15_Original.Download.zip)

Didn't see any MD5 but as the name says here is one of the downloads I used and also the same File copied back from the i9100 to check if the file somehow corrupted while beeing copied.

Thanks for the quick response btw. ^^

I hope you can do something about it because I really wouldn't like to go back to the stone ages and learn to use Odin again for a repartition. You're saving a lot of ppl a lot of their lifetime. (:

**Comment by Lanchon** [comment]
i was right, the downloads are corrupted. your download toolset -whatever it is- opened and repacked the zip file in the process, stripped the signature, put all my files inside a strange directory that it created, and who knows what else.

**Comment by Lanchon** [comment]
the file download page shows the MD5. check it if in doubt when you download again.

**Comment by Lanchon** [comment]
lol you downloaded and tried to install the source code!
read the docs and download from the right place :)

**Comment by Slamraptor** [comment]
You're right goth damnit xD
Thanks for the help anyway man. ^^

Finished repartioning and am recovering my backups right now.

_facepalm_
