### ISSUE TITLE
error installing zip

### ISSUE THREAD

**Issue by melicheradam** [Lanchon/REPIT#43]
Hello,i have the exact problem as the Slamraptor (no MD5),my download seems ok so i´m out of ideas what is the problem here..can you please help?
[lanchon-repit-XXXXXXXX-system=1-data=6-sdcard=max-preload=0.5+wipe-i9100.zip](https://github.com/Lanchon/REPIT/files/368052/lanchon-repit-XXXXXXXX-system.1-data.6-sdcard.max-preload.0.5.wipe-i9100.zip)
I tried the master version and 20160406 version and both coming up with the same error..
Idk if i´m blind or what but i can´t even find the MD5 file on website o.O

**Comment by Lanchon** [comment]
lol you downloaded the source code. read the docs and download from the right place jeez!
