### ISSUE TITLE
Samsung Galaxy S5 G900F (klte)

### ISSUE THREAD

**Issue by wecip** [Lanchon/REPIT#44]
[repit-dump.log.txt](https://github.com/Lanchon/REPIT/files/372268/repit-dump.log.txt)
Hi Lanchon, i attached the log also on pastebin
http://pastebin.com/WcGjnv7K

Samsung Galaxy S5 G900F klte
Recovery TWRP 3.0.2-2 official
Boeffla kernel 2.1 beta 3 Marshmallow
Rom xXx NoLimits 5.0 G900FXXU1CPG1
Stock (MM) partition layout

Regards

**Comment by Lanchon** [comment]
hi!

do you want to shrink system? or is it something else?
BTW, what would be your preferred system size?

thanks you

**Comment by wecip** [comment]
Hi, i want more space on internal storage
You can decrease preload?
On system at the moment i have 250mb of free space
Sorry for my english
Thank you

**Comment by Lanchon** [comment]
preload is 50MB, i wouldnt touch it!!!

if you want more space, assuming you have a custom rom, then install the custom rom and 'nano' gapps. then install all the other gapps you want from the market. gapps installed in the system use TWICE the space as those installed from market.

after you do this, system should be around 750MB used. then you can REPIT to resize system to 1GB and gain 1.5GB extra space for /data.

**Comment by Lanchon** [comment]
if you don't want to do all this, you can simply disable some google apps you use in the UI. you can at least recover some space.

**Comment by Lanchon** [comment]
done

**Comment by wecip** [comment]
Ok we can try to repit the system, in a sammy rom are enough 1GB of system?

**Comment by Lanchon** [comment]
no! only repit if u use a custom rom

**Comment by wecip** [comment]
Custom rom like AOSP?

**Comment by Lanchon** [comment]
any aosp based rom. you can use CM or omni for instance. if you never used custom roms you shouldnt try to repartition ur phone immediately. maybe you need more experience before that.

**Comment by wecip** [comment]
Ok but i want to use a stock rom
You can do something for work with stock rom?

**Comment by Lanchon** [comment]
no, risky.

**Comment by wecip** [comment]
hi, it says ''unable to reread the partition table'' how to fix

**Comment by Lanchon** [comment]
please read the docs

**Comment by wecip** [comment]
Hi,i read the docs and i have execute repit on /tmp    and it says the same thing,maybe my phone is encrypted? And how to encrypt?

**Comment by Lanchon** [comment]
well since you don't post a log (as the docs say :) ) then i can't really help you.

if your phone is encrypted then TWRP should either ask for the unlock code or it should be unable to mount /data in the mount menu and show its contents its file manager.

to solve the unable to unmount error:
-make sure repit is in the internal memory of the phone (not the external sdcard).
-go to mount menu and disable MTP.
-disconnect from any PC or host.
-reboot recovery.
-flash repit from internal memory; it will fail.
-go to mount menu and manually unmount all partitions.
-flash repit from /tmp.

if it sill gives you trouble, remove the sdcard and repeat the process.

in case of trouble, I NEED THE LOG.

**Comment by wecip** [comment]
Here is the log file
[recovery.log.txt](https://github.com/Lanchon/REPIT/files/391965/recovery.log.txt)

**Comment by Lanchon** [comment]
did you follow the exact steps above?

if yes, and your phone is not encrypted, then i don't know whats wrong. you might have better luck with a different TWRP build.

**Comment by wecip** [comment]
Log with TWRP 3.0.2-0
[recovery2.log.txt](https://github.com/Lanchon/REPIT/files/392056/recovery2.log.txt)
Log with TWRP 3.0.0-0
[recovery3.log.txt](https://github.com/Lanchon/REPIT/files/392057/recovery3.log.txt)
And same error with TWRP 2.8.7.0

**Comment by Lanchon** [comment]
im travelling thru europe without much free time. did you or did you not follow the exact steps i sent above? thanks!

**Comment by wecip** [comment]
Yes i followed all steps

**Comment by Lanchon** [comment]
i don't know what's happening in your case. since this issue is a port request, i have branched the bug report [here](https://github.com/Lanchon/REPIT/issues/45). for the time being, i can't help you in a meaningful way.

**Comment by Lanchon** [comment]
**WARNING !!! WARNING !!! WARNING !!!**

in view of [recent events](https://github.com/Lanchon/REPIT/issues/55), and taking into account that this device is Qualcomm-based, **the possibility of hard-bricking by repartitioning cannot be ruled out.**

potential testers proceed at your own peril.

**Comment by Lanchon** [comment]
there has been a new development regarding detection of GPT signatures via strings in the bootloader. it is now known that this method can result in false positives.

please [see the details here](https://github.com/Lanchon/REPIT/issues/28#issuecomment-273797302).
