### ISSUE TITLE
partition 11 corrupted

### ISSUE THREAD

**Issue by engmux** [Lanchon/REPIT#48]
Hello,
First of all, Thank you for your work. It's very much appreciated.

I have the following error (in logs). I am running the latest NightOwl CM13 on my Note N7000.

[lanchon-repit.txt](https://github.com/Lanchon/REPIT/files/477764/lanchon-repit.txt)
[recovery.txt](https://github.com/Lanchon/REPIT/files/477763/recovery.txt)

I re-partitioned months ago. Yesterday I flashed the bauner's ROM (I was with the NightOwl CM12) using the Philz Recovery and the sdcard0 is corrupted now. I flashed the TWRP recovery, tried to re-format, re-partition with your tool and I have the error in logs. So now my Note works fine but without sdcard0 and I have only 6GB available :(((

Solved: I just needed to format the partition. Sorry for opening the issue :-)

Cheers,
Engmux

**Comment by Lanchon** [comment]
your sdcard partition seemed to be ext4 but you told REPIT it was vfat. REPIT did not find valid vfat so it chose not to continue.
