### ISSUE TITLE
Unable to download the latest version

### ISSUE THREAD

**Issue by Leon99** [Lanchon/REPIT#50]
![image](https://cloud.githubusercontent.com/assets/6840381/19012230/de19e48e-87f2-11e6-8324-739021b89b46.png)
Getting 

> no mirrors found

for the latest i9100 version.
Previous version downloaded fine, but the current documentation is not valid for it, so I spent some time to figure out that G should be omitted from the spec.

**Comment by jerryhou85** [comment]
I think it's something wrong with androidfilehost. @Lanchon better re-upload all the files to 0923... :'(

> SYSTEM NOTICE: Devs: We have fixed the upload issue where when uploading multiple files at a time caused some files to say no mirrors found. Please re-upload files that were affected. We are working on a fix for multiple ftp imports. Sorry for the slowness and errors loading the site. Will be fixed this week.

**Comment by Lanchon** [comment]
thank you! i did this already, problem fixed, too bad i just saw this report now, sorry about that :-/
thanks again for reporting!

**Comment by MartinX3** [comment]
@Lanchon Same with  
https://androidfilehost.com/?fid=4349826312261630576  
"lanchon-repit-20170115-system=max-cache=32M+wipe-flo.zip"  
:(

**Comment by Lanchon** [comment]
i added the files to the [release](https://github.com/Lanchon/REPIT/releases/tag/2017-01-15) page
