### ISSUE TITLE
Samsung Galaxy S III LTE (i9305)

### ISSUE THREAD

**Issue by nishimura-san** [Lanchon/REPIT#54]
Just wanted to ask you Lanchon to support i9300's brother, i9305. If you want a partition dump, then here you go:

drwxrwxr-x 2 system radio 360 2016-10-15 20:58 .
drwxr-xr-x 4 root   root  460 2016-10-15 20:58 ..
lrwxrwxrwx 1 root   root   20 2016-10-15 20:58 BOOT -> /dev/block/mmcblk0p8
lrwxrwxrwx 1 root   root   20 2016-10-15 20:58 BOTA0 -> /dev/block/mmcblk0p1
lrwxrwxrwx 1 root   root   20 2016-10-15 20:58 BOTA1 -> /dev/block/mmcblk0p2
lrwxrwxrwx 1 root   root   21 2016-10-15 20:58 CACHE -> /dev/block/mmcblk0p12
lrwxrwxrwx 1 root   root   20 2016-10-15 20:58 EFS -> /dev/block/mmcblk0p3
lrwxrwxrwx 1 root   root   21 2016-10-15 20:58 HIDDEN -> /dev/block/mmcblk0p14
lrwxrwxrwx 1 root   root   21 2016-10-15 20:58 OTA -> /dev/block/mmcblk0p15
lrwxrwxrwx 1 root   root   20 2016-10-15 20:58 PARAM -> /dev/block/mmcblk0p7
lrwxrwxrwx 1 root   root   21 2016-10-15 20:58 RADIO -> /dev/block/mmcblk0p10
lrwxrwxrwx 1 root   root   20 2016-10-15 20:58 RECOVERY -> /dev/block/mmcblk0p9
lrwxrwxrwx 1 root   root   21 2016-10-15 20:58 SYSTEM -> /dev/block/mmcblk0p13
lrwxrwxrwx 1 root   root   21 2016-10-15 20:58 TOMBSTONES -> /dev/block/mmcblk0p11
lrwxrwxrwx 1 root   root   21 2016-10-15 20:58 USERDATA -> /dev/block/mmcblk0p16
lrwxrwxrwx 1 root   root   20 2016-10-15 20:58 m9kefs1 -> /dev/block/mmcblk0p4
lrwxrwxrwx 1 root   root   20 2016-10-15 20:58 m9kefs2 -> /dev/block/mmcblk0p5
lrwxrwxrwx 1 root   root   20 2016-10-15 20:58 m9kefs3 -> /dev/block/mmcblk0p6

If you need anything more just tell me. I got TWRP 3.0.2-1 running on it, bootloader unlocked (duh) and is running Temasek's CM13.

This is why i want to repartition:

_/dev/block/mmcblk0p13           1548144  1157072    391072  75% /system_
/dev/block/mmcblk0p3              20144     4324     15820  22% /efs
/dev/block/mmcblk0p12           1032088    21756   1010332   3% /cache
/dev/block/mmcblk0p11            258016    18616    239400   8% /tombstones
/dev/block/mmcblk0p10            204580    46428    158152  23% /firmware
_/dev/block/mmcblk0p16          11574840  4958024   6616816  43% /data_

**Comment by the-gangster** [comment]
You should at least provide an output of repit-dump to him for your port request, no matter how similar it is to the already ported i9300...
[read here](https://github.com/Lanchon/REPIT/tree/master/device-dump)

**Comment by Lanchon** [comment]
yes, please do follow the previous link. thank you both!

**Comment by nishimura-san** [comment]
Okay, my bad. I haven't found that. Here is the output of the device-dump.

device: i9305, m3, m3xx
recovery: TWRP 3.0.2-1, official from twrp.me
kernel: 3.0.101-boeffla
Boeffla-Kernel-v5.1-beta7-CM13.0-i9305-20160830@andip71
#1 unofficial by limjh16
ROM: Temasek CM13 V11 6.0.1 MOB30Z
Partition layout: stock

here is the dump: [repit-dump.log](http://pastebin.com/ApXtkRAS)

Or here: (rename to log) 
[repit-dump.txt](https://github.com/Lanchon/REPIT/files/531797/repit-dump.txt)

**Comment by Lanchon** [comment]
IMPORTANT: please read this before proceeding... https://github.com/Lanchon/REPIT/issues/55

**Comment by Lanchon** [comment]
if you agree to test, you can untar and flash this file according to REPIT instructions on project page:
[lanchon-repit-i9305_UNTESTED.tar.gz](https://github.com/Lanchon/REPIT/files/536850/lanchon-repit-i9305_UNTESTED.tar.gz)
- will shrink system to 1GB and preload and cache to minimum, and give you 2 extra GB for data storage.
- no data will be discarded outside of preload and cache.
- the process will check the viability of reducing system to 1GB before proceeding with any changes to your phone.

**Comment by nishimura-san** [comment]
Modifying partitions right now. Wish me luck.

**Comment by nishimura-san** [comment]
Hehe. I like to live dangerous :) 16% battery, charging but still dropping in percentage. 13012 MiB in. Nothing bad so far.

**Comment by nishimura-san** [comment]
15% now. only about 2K MiB. REALLY wish me luck.

**Comment by nishimura-san** [comment]
ASTOUNDING SUCCESS. 12.52GB now, had to keep system the same 1.5GB because i want to add stuff on the System partition. I will upload whatever you want as long as I can get it. Logs? Where are they stored? I had to flash the zip from /tmp, so I don't know from where to get the log.

**Comment by Lanchon** [comment]
hi,

glad it worked, thanks for reporting!
no logs needed if everything was ok.

i can't recommend the 1.5G /system.
i suggest you read [this](https://github.com/Lanchon/REPIT/issues/56) and maybe REPIT again.

**Comment by Lanchon** [comment]
ok i9305 version pushed and released.

i'm closing but you can still comment here.
