### ISSUE TITLE
Sony Xperia L (taoshan) c2104

### ISSUE THREAD

**Issue by mgarridoe** [Lanchon/REPIT#61]
[repit-dump.log.txt](https://github.com/Lanchon/REPIT/files/638169/repit-dump.log.txt)

your exact device and device codename.
Sony Xperia L (taoshan) c2104
your recovery (version? official? if not where did you get it?).
TWRP 3.0.0.0 oficial
your kernel.
3.4.0-g8ce6fe2
your rom.
Cyanogenmod 12.1-20160822
is your device running the stock partition layout or is it already modified?
Stock

Thank you in advance.

Kind regards.

Miguel

**Comment by mgarridoe** [comment]
Sorry here is the dump file

Kind Regards

**Comment by Lanchon** [comment]
hi, thanks!

interesting... what a lousy stock partition layout, lol.
what is the "ftma" partition? got any info?
is your bootloader unlocked?
i'm downloading a stock image to look into some things

**Comment by Lanchon** [comment]
in recovery, from the PC, could you please run:

`adb pull /dev/block/platform/msm_sdcc.1/by-name/aboot`

then zip and post the resulting aboot file here

**Comment by mgarridoe** [comment]
[aboot.zip](https://github.com/Lanchon/REPIT/files/639644/aboot.zip)

The bootloader is unlocked (since day 0 LOL)
I've googled for ftma partition with no luck. I guess it has something to do with FlashTool. Pulling out right now and trying to mount in Linux. I'll tell you my findings later.

**Comment by Lanchon** [comment]
you can post it here. it comes in the stock image, so it's not personalized for your phone. but the stock image is in an unknown format.

**Comment by mgarridoe** [comment]
[ftma.zip](https://github.com/Lanchon/REPIT/files/639669/ftma.zip)

-rwxr-x--- 1 root root  176 mar 25  2014 cci-flex.sh
-rw-r--r-- 1 root root  501 mar 25  2014 cci.prop
drwx------ 2 root root 4096 dic 31  1969 lost+found

**Comment by Lanchon** [comment]
thanks for aboot.

```
$ strings aboot | grep -i gpt | grep -i sign

GPT: (WARNING) Primary signature invalid
  GPT: Primary and backup signatures invalid
  GPT: Primary signature invalid cannot write GPT
  GPT: Backup signature invalid cannot write GPT
```

i'm sad to inform that there are strings in the bootloader that hint to a signed GPT. your BL might or might not enforce GPT signatures.

in case it does, altering the GPT might brick the phone. the expectation is that not even fastboot would work, and the phone would drop to one of the QCOM bulk interfaces.

to recover from that situation requires qualcomm's tools and leaked factory files for your device. do you know if recovery is possible for your phone?

there's a real hard-bricking possibility here. i can't really recommend going forward. what do you think?

**Comment by mgarridoe** [comment]
Sad to read that.

Right now I can't risk the phone.

I'm sorry, thank you for your time.

I'm going to link this issue in the thread for CM13 on Xperia L hopefully someone can continue.

**Comment by Lanchon** [comment]
good call. very sorry, nice working with you though.

**Comment by Lanchon** [comment]
note to self:
CM labels: C2105,C2104,c2105,c2104,taoshan

**Comment by Lanchon** [comment]
i'm going to close this but i'll reopen if a someone wants to move it forward.

**Comment by Lanchon** [comment]
there has been a new development regarding detection of GPT signatures via strings in the bootloader. it is now known that this method can result in false positives.

please [see the details here](https://github.com/Lanchon/REPIT/issues/28#issuecomment-273797302).
