### ISSUE TITLE
Nook HD (hummingbird)

### ISSUE THREAD

**Issue by BultoPaco** [Lanchon/REPIT#64]
Device:  BN Nook HD (hummingbird)

Recovery:  twrp-3.0.1-0-hummingbird from amaces box file repository associated with "Marshmallow & Nougat (AOSP/CM1[34]) for Nook HD & HD+"
 
Kernel:  3.0.101 dmaces@gc-xenial #1 Wed Dec 7 16:12:32 EST 2016

Rom:  CM 14.1-20161207-UNOFFICIAL-hummingbird from amaces box file repository

I am running the device with stock partition layout.  I had to zip the log file to attach it here.  I really appreciate your work and hope you can help me whenever time allows -- no expectation, no entitlement:)
[repit-dump.zip](https://github.com/Lanchon/REPIT/files/669200/repit-dump.zip)

**Comment by Lanchon** [comment]
[repit-dump.log](http://pastebin.com/raw/R3FpRSXz)

**Comment by Lanchon** [comment]
hi, thanks!

it seems that your device would benefit from a repit port.

could you please list the contents of /factory? in TWRP, connect to PC and from there:
`adb shell ls -laR /factory`
or:
`adb shell ls -laR /factory >factory-list.txt`

thanks!

**Comment by BultoPaco** [comment]
I may have reached my level of incompetence!  Here is the results of my attempt to get the /factory contents with adb while in TWRP on the hummingbird.  I'm obviously doing something wrong.

C:\Program Files (x86)\Minimal ADB and Fastboot>adb devices
List of devices attached
0123456789ABCDEF        recovery


C:\Program Files (x86)\Minimal ADB and Fastboot>adb shell ls -laR /factory-list.txt
ls: /factory-list.txt: No such file or directory

C:\Program Files (x86)\Minimal ADB and Fastboot>adb shell ls -laR /factory
ls: /factory: No such file or directory

C:\Program Files (x86)\Minimal ADB and Fastboot>adb shell ls
boot                          proc
bootdata                      property_contexts
cache                         recovery
charger                       res
data                          root
default.prop                  sbin
dev                           seapp_contexts
emmc                          selinux_version
etc                           sepolicy
external_sd                   service_contexts
file_contexts                 sideload
fstab.hummingbird             supersu
init                          sys
init.rc                       system
init.recovery.hummingbird.rc  tmp
init.recovery.usb.rc          twres
initlogo.rle                  ueventd.hummingbird.rc
license                       ueventd.rc
oem

**Comment by Lanchon** [comment]
>adb shell ls -laR /factory
>ls: /factory: No such file or directory

apparently TWRP doesn't mount the factory partition in /factory.

you'd need to pull the partition and send it over. but it has sensitive data about your device (mac addresses, serial number, etc.) so if you pull it you'll have to share it privately with me. my email is lanchon at the very known google mail system.

to pull the partition, type this at the PC:
`adb pull /dev/block/mmcblk0p7 factory.img`

the file is around 0.5 GB. you can use dropbox or any other service and send me a link.

otherwise you can try mounting the partition by yourself using `adb shell` and linux commands, if you feel adventurous.

**Comment by Lanchon** [comment]
hi,

i'm very sorry for the long delay.
the port is ready, look it up in the downloads section.

also, be sure to take a look at [this](https://github.com/Lanchon/REPIT/issues/59) and [this](https://forum.xda-developers.com/nook-hd/development/nook-hd-repit-enlarge-data-partitions-t3503615/post69705159#post69705159).
