### ISSUE TITLE
Samsung Galaxy S GT-I9000 (galaxysmtd)

### ISSUE THREAD

**Issue by Viksie** [Lanchon/REPIT#65]
Device Model: Samsung Galaxy S - GT-I9000
Recovery: TWRP 3.0.2-0
Android version: 6.0.1
CyanogenMod version: 13.0-20160613-UNOFFICIAL-galaxysmtd
GAPPS version: open_gapps-arm-6.0-pico-20161217.zip
Baseband version: I9000XXJVT
Partition Layout: Still Stock

Contemplating the maximum possible space for the data partition with system & data as F2FS with no internal sdcard in all regards, ie. -system=2G+wipe-data=6G+wipe-preload=min+wipe

Thanks for your help.

[repit-dump.log.zip](https://github.com/Lanchon/REPIT/files/673085/repit-dump.log.zip)

**Comment by Lanchon** [comment]
[repit-dump.log](http://pastebin.com/raw/w8mGGRUU)

**Comment by Lanchon** [comment]
hi,

unfortunately your device is partitioned in the very old MS-DOS style instead of using a GPT.
REPIT does not support MS-DOS partition tables.

i'm sorry about this, and also for the late reply.

best,
Lanchon
