### ISSUE TITLE
Installation fails with latest TWRP/repit on a I9100

### ISSUE THREAD

**Issue by markusfisch** [Lanchon/REPIT#66]
Installation of the latest lanchon-repit-20160923-system=1G-data=6G-sdcard=max-preload=min+wipe-i9100.zip from the download link in the README.md fails with:

```
...
Installing update...
E:Can't run /tmp/update_binary (No such file or directory)
E :Error in /tmp/sideload/package.zip
(Status 255)
```
The reason seems to be that the shebang in /tmp/update_binary references #!/sbin/sh which does not exist.

The device is a standard I9100 with the latest official updates from Samsung:
```
Model: GT-I9100
Android-Version: 4.1.2
Baseband: I9100XXLS8
Kernel-Version: 3.0.31-889555 dpi@DELL228 #3 SMP PREEMPT Thu Jan 31 14:48:54 KST 2013
Buildnumber: JZO54K.I9100XWLSD
```

I tried the latest repit release for the I9100 from the linked [androidfilehost.com](https://www.androidfilehost.com/?w=files&flid=119974):
```
lanchon-repit-20160923-system=1G-data=same-sdcard=max-preload=min+wipe-i9100.zip
806KB Oct 02, 2016 | 01:16PM
```
As well as
```
lanchon-repit-v0.1-sys1GB-data6GB-i9100.zip
8.9KB Feb 13, 2016 | 06:56PM
```
from oldfiles/. Same result. I renamed the first file according the README to have data partition of 6G:
```
lanchon-repit-20160923-system=1G-data=6G-sdcard=max-preload=min+wipe-i9100.zip
```

The flashing procedure was as follows:
* Starting with above described device with latest official updates and standard Samsung software.
* Enabled USB debugging in developer settings to allow adb communication.
* Downloading late [twrp-3.0.2-1-i9100.img](https://dl.twrp.me/i9100/) and [lanchon-repit-20160923-system=1G-data=same-sdcard=max-preload=min+wipe-i9100.zip](https://www.androidfilehost.com/?fid=312968873555002742)
* Renamed lanchon-repit to specify a 6GB data partition:
```sh
$ mv lanchon-repit-20160923-system=1G-data=same-sdcard=max-preload=min+wipe-i9100.zip lanchon-repit-20160923-system=1G-data=6G-sdcard=max-preload=min+wipe-i9100.zip
```
* Pushing lanchon-repit...6G...zip onto sdcard with
```sh
$ adb push lanchon-repit-20160923-system=1G-data=6G-sdcard=max-preload=min+wipe-i9100.zip /sdcard/
```
* Move /sdcard/lanchon-repit... to external SD card (can't be done with adb because shell user can't write to /storage/extSdCard) with Samsung's pre-installed file manager app.
* Power off device then holding down Volume *Down*, Home and Power buttons to enter download mode.
* Flash TWRP image with heimdall (version v1.4.1) from (Ubuntu) Linux:
```sh
$ heimdall flash --RECOVERY twrp-3.0.2-1-i9100.img
```
* Power off device then holding down Volume *Up*, Home and Power buttons to enter custom recovery.
* Navigate to "apply update from external sd card"
* Navigate to lanchon-repit-20160923-system=1G-data=6G-sdcard=max-preload=min+wipe-i9100.zip
* Press power

Am I missing something important here?

PS: sorry for the piggybacking of [#20](https://github.com/Lanchon/REPIT/issues/20) but I'd thought you'd rather like to have one issue for a problem and not multiple issues for the same problem.

**Comment by the-gangster** [comment]
You missed the fact, that the recovery you finally launched is not the TWRP-recovery that you flashed in the step before, but still the stock recovery, as the recovery in the recovery-partition is only launched by kernels that support [IsoRec](https://forum.xda-developers.com/galaxy-s2/orig-development/isorec-isolated-recovery-galaxy-s2-t3291176).
One option would be flashing an IsoRec-supporting DorimanX kernel for your 4.1.2 JB.
[This one should work](https://forum.xda-developers.com/galaxy-s2/development-derivatives/kernel-dorimanx-jb-4-1-2-t3106241)

**Comment by markusfisch** [comment]
Ah, thank you very much! So many pitfalls...

**Comment by Lanchon** [comment]
thanks so much, @the-gangster.

@markusfisch, why do you use stock? the stock kernel is severely broken by a couple of high profile bugs such as fpbug. the old android don't even trim the emmc.

you should at a minimum use CyanogenMod kitkat, the latest nightly that was available (or even better, a newer unofficial build) with a trim-enabled kernel such as mine. CM 13 apparently works well too.

**Comment by markusfisch** [comment]
@Lanchon yes, I've already updated the kernel. I just wasn't aware the stock kernel wouldn't boot the recovery partition and tried to change as little as possible.
