### ISSUE TITLE
Redmi Note 1LTETD (dior)

### ISSUE THREAD

**Issue by wfjsw** [Lanchon/REPIT#68]
[repit-dump.log.txt](https://github.com/Lanchon/REPIT/files/706397/repit-dump.log.txt)
Device Model: Redmi Note 1LTETD
Recovery: TWRP 3.0.2-0(Official)
Android version: 7.1.1
Mokee version: MK71.1-dior-201701150542-NIGHTLY
Kernel: 3.4.0-g26e4aff-00643-g14e7e46
Partition Layout: Stock

Wanna install at least OpenGApps Pico(But the ROM size is still expanding)

Thanks for your help!

**Comment by Lanchon** [comment]
what's wrong with #46??

you should be able to use the "-dior" build in the downloads!

btw, if you want to quickly grow /system without touching (and risking) /data at all, then use this config:
`system=1160M-cache=32M+wipe-data=same`

**Comment by wfjsw** [comment]
Oops I am sorry :x
