### ISSUE TITLE
Dior script fails

### ISSUE THREAD

**Issue by ghost** [Lanchon/REPIT#71]
![screenshot_2017-02-14-13-29-20 1](https://cloud.githubusercontent.com/assets/7571095/22945400/6dc8f2fc-f2f4-11e6-99cd-8fa3484d9e1e.png)
Tried both January and September scripts.
Device: Dior
TWRP 3.0.3-0
/tmp/updater: env/script[1620] : ${@: 2}: bad substitution 
[ERROR 1]

**Comment by Lanchon** [comment]
your version of TWRP is defective, it probably has toybox instead of busybox. get a functional TWRP and try again. 3.0.2-x probably works fine.

**Comment by ghost** [comment]
You were right. I'll drink a beer in your honor.

Thanks.
