### ISSUE TITLE
Motorola Moto X Pure Edition / Style (2015) (clark)

### ISSUE THREAD

**Issue by cqkking** [Lanchon/REPIT#74]
Moto X style 2015 / clark.
TWRP 3.0.2-0 official downloaded from twrp website
Kernel: 3.10.84-perf-gb67345b
Official ROM: MPHS24.107-58-5
My device is running the stock partition layout
[repit-dump.log.TXT](https://github.com/Lanchon/REPIT/files/944508/repit-dump.log.TXT)

You can see my /system is oversized and there is ~1GB free, and /userdata is small because I install a lot apps.

**Comment by Lanchon** [comment]
hi, 

some newer devices have a signed GPT (partition table). on such devices, altering the GPT hard-bricks the device. this is the reason i mostly stopped development of REPIT.

make sure you read [this](https://github.com/Lanchon/REPIT/issues?q=locked-down+GPTs). you can try running the `strings` command on images of your bootloaders (or post the images here) to get hints on the situation of your device. `strings` can usually rule out signatures, but it can also result in false positives.

to recover from a hard brick you would need an image of your eMMC and the ability to program the eMMC with a JTAG probe. if you do not know what JTAG is, then assume you have no way to recover your device.

please decide whether you want to risk testing a REPIT port on your device.

thanks!

**Comment by Lanchon** [comment]
hi,

sorry for the long delay. are you still interested in this?

thanks!

**Comment by cqkking** [comment]
Thanks for reaching out to me. No, not interested anymore, I switched the
phone.

Kane

Lanchon <notifications@github.com> 于 2019年11月15日周五 00:54写道：

**Comment by Lanchon** [comment]
thank you!

i'll reopen the issue if somebody is interested.
