### ISSUE TITLE
Maguro download seems to be down

### ISSUE THREAD

**Issue by RealRen0** [Lanchon/REPIT#75]
I tried to redownload Repit today for my maguro because I deleted my previous Repit ZIP by mistake. I was surprised as I saw on AFH: "Oops! No mirrors found!". Could you please reupload the file or is this just an error occured by me?

**Comment by the-gangster** [comment]
Just tested and it worked. (I was kicked to USA#2 Pennsylvania)

**Comment by RealRen0** [comment]
I have tested it again right now and I m able to find the mirror USA#2 Pennsylvania  too. Sorry for the inconvenience.
