### ISSUE TITLE
Samsung Note SGH-i717

### ISSUE THREAD

**Issue by BenMJimenez** [Lanchon/REPIT#76]
Samsung Note SGH-i717, rooted, unlocked, running customer rom 5.1 , and TWRP. If it's possible to recofigure my system partition to about 5GB

[repit-dump.txt](https://github.com/Lanchon/REPIT/files/1034784/repit-dump.txt)

**Comment by Lanchon** [comment]
hi,

sorry for the huge delay. are you still interested in this?

thanks!

**Comment by Lanchon** [comment]
i'll reopen the issue if somebody is interested. sorry for for being unavailable for such a long time.
