### ISSUE TITLE
 Samsung Galaxy J7 SM-J700F/D (j7elte)

### ISSUE THREAD

**Issue by arsalan-hussain** [Lanchon/REPIT#82]
[repit-dump.log](https://github.com/Lanchon/REPIT/files/1698777/repit-dump.log)
Device : Samsung Galaxy J7 2015 (EXYNOS)
Device code name : SM-J700F/D
Recovery : TWRP - 3.2.1.0 -Official 
Kernel : Hyperion ( linux 3.10.x)
ROM (Custom ROM) : RADIOACTIVE ROM.
LINK OF ROM(incase..) : https://forum.xda-developers.com/galaxy-j7/development/rom-t3713641
**DEVICE IS RUNNING WITH STOCK PARTITION LAYOUT**
I have about 9 GBs of free space after Flashing ROM I want to  increase the size of System Partion by another 1GB. 
Kindly help me !!  😫

**Comment by Lanchon** [comment]
hi, 

some newer devices have a signed GPT (partition table). on such devices, altering the GPT hard-bricks the device. this is the reason i mostly stopped development of REPIT.

make sure you read [this](https://github.com/Lanchon/REPIT/issues?q=locked-down+GPTs). you can try running the `strings` command on images of your bootloaders (or post the images here) to get hints on the situation of your device. `strings` can usually rule out signatures, but it can also result in false positives.

to recover from a hard brick you would need an image of your eMMC and the ability to program the eMMC with a JTAG probe. if you do not know what JTAG is, then assume you have no way to recover your device.

please decide whether you want to risk testing a REPIT port on your device.

thanks!

**Comment by Lanchon** [comment]
hi,

sorry for the long delay. are you still interested in this?

thanks!

**Comment by arsalan-hussain** [comment]
Hi sorry for not replying. I am not using that device anymore. But thank
you for considering my request.

Cheers.

**Comment by Lanchon** [comment]
thanks! i'll reopen this issue if somebody is interested.
