### ISSUE TITLE
Desire C - with cm12 and small partition shows Error: Can't have overlapping partitions.

### ISSUE THREAD

**Issue by Cello75** [Lanchon/REPIT#86]
Fortunately, I managed to unlock Bootloader, backup Stock Rom, flash TWRP, cm12x by golfu (xda-developers), unlock Sim (all by myself, easily), get most android apps working (apart from BT), etc. within my 5-year-old HTC Desire C (for that Mom can finally use Whatsapp...) as a beginner's mobile phone and I feel I'm stuck with resizing internal memory - please do not ask why I wouldn't use external microsd - I'm using further one 16GB-microsd Card but it won't show internal memory inside of ANY FileManager-app, in case my external sandisk-microsd Card is plugged in .. 
With this great application REPIT by LANCHON I could only determine that there is some strange error, like: 
Warning! Main partition table overlaps the first partition by 33 blocks!
You will need to delete this partition or resize it in another utility.
[repit-dump.log](https://github.com/Lanchon/REPIT/files/2160014/repit-dump.log)

What is another utility? gparted or parted, maybe? Yet,
 I'm able to connect this cute HTC Desire C to my Ubuntu18.04 and either adb or fastboot the named device.. 
PLease help, because I'm overwhelmed with special tasks in my surrounding at the moment in life. Thanks so much for any good advice ..  

PS: I only just have some 30-330 MB internal memory left - is there any way to use more resp. resize internal memory?: )

**Comment by Lanchon** [comment]
```
***************************************************************
Found invalid GPT and valid MBR; converting MBR to GPT format.
***************************************************************
```

you device does not use the GPT partition format. REPIT will never work on it.

thanks!
