### ISSUE TITLE
I would love to use this application, but I don't know where to start

### ISSUE THREAD

**Issue by terry-sydaus** [Lanchon/REPIT#90]
Hi Lanchon,
I have read the readme.md and I am still unable to work out how to utilise this application for changing the size of my /data partition on my Samsung Galaxy S2. This is a complete reflection on my lack of knowledge and I was wondering if you could step me through what I need to do to make this work for me.
Many thanks.

**Comment by terry-sydaus** [comment]
OK, I worked out how to use this tool.
I am now getting the following error while running this on my Samsung S2, with the version of TWRP that is closest to that specified in the readme.md (ie. 3.0.2-0). 
...
FATAL: required tool 'parted' missing (please use a recent version of TWRP to run this package) [ERROR 1]

Any thoughts on how I can make this work. My lanchon repit file name is:
lanchon-repit-20160317-system=1.5G-data=10G-sdcard=max-preload=min-i9100.zip

I renamed it from the file I downloaded with a similar name.

**Comment by the-gangster** [comment]
You should have used the latest version of repit. The error with that version of twrp (and its binaries) was already fixed long ago.
;-)
