### ISSUE TITLE
Samsung Galaxy S2 Plus (i9105p)

### ISSUE THREAD

**Issue by camp0s** [Lanchon/REPIT#91]
Hi, I'd like to ask for an official port for the Samsung Galaxy i9105p.

I saw this post: on XDA:
https://forum.xda-developers.com/android/help/samsung-galaxy-s2-plus-i9105-t3696279

..and I got the dump file from your script! I'm unable to attach the .log file here (github says _something went really wrong, and we can't process that file_).

Instead of pasting the code (inside code tag - horrible) I've upped the file in the post on the XDA forum, feel free to reupload it here if it works.

Regarding the questions:

**your exact device and device codename.**
Samsung Galaxy i9105p, s2vep (has NFC under the battery sticker).
The version without NFC is called: Samsung Galaxy i9105, s2ve, they have the same memory structure.

**your recovery (version? official? if not where did you get it?).**
TWRP 3.1.1.-0 flashed with ODIN; found googling.

**your kernel.**
Stock for sure, don't know the version, but nothing was flashed.

**your rom.**
Stock latest 4.2.2 Rom official Samsung.

**is your device running the stock partition layout or is it already modified?**
Stock, only wiped.

Well, let me know if you need anything more.
Cheers!

**Comment by Lanchon** [comment]
are you still interested in this?

thanks!

**Comment by Lanchon** [comment]
i'll reopen the issue if somebody is interested. sorry for for being unavailable for such a long time.
