### ISSUE TITLE
blockdev: /dev/block/mmcblk0: Device or resource busy

### ISSUE THREAD

**Issue by zhro** [Lanchon/REPIT#92]
I'm trying to use this on my Samsung Galaxy Nexus (Verizon) - toro. I have gone through the following procedure:

I am using `TWRP 3.2.1-0` and attempting to flash `lanchon-repit-20170115-system=1G-cache=62M+wipe-data=same-toro.zip`.

Procedure:

```
Install ROM -> ua_tuna-7.1.2-20181227-1745.zip
Wipe -> Cache/Dalvik/Data/Internal Storage
adb push -> lanchon..zip
Mount -> Disable MTP

(Unplug from PC)
(Reboot recovery)

Install -> /sdcard/../lanchon..zip

umount: can't umount /sdcard: Device or resource busy
...

Install -> /tmp/lanchon..zip

info: unmounting all partitions
blockdev: /dev/block/mmcblk0: Device or resource busy
 
FATAL: unable to reread the partition table (please disable MTP in TWRP's 'Mount' menu (or disconnect from PC), reboot TWRP and run this package again; run it immediately after boot up, do not enable USB mass storage; note that you might be told to run it yet again from '/tmp'; make sure your phone is not encrypted: encrypted phones are not supported)
```

Why is this failing?

The problem seems to be with repit being unable to unmount all partitions.

**Comment by Lanchon** [comment]
please seek help with other toro users. you are doing everything right, but still the kernel is not unmounting. please remember that REPIT will not work if your device is encrypted. could this be your case?

**Comment by zhro** [comment]
My device is not encrypted.

**Comment by Lanchon** [comment]
were you able to solve this?

maybe you can try using an older TWRP, from the date other users were successful.

how do you know that your device is not encrypted?

**Comment by Lanchon** [comment]
maybe this helps: https://github.com/Lanchon/REPIT/issues/35

**Comment by Lanchon** [comment]
i'll reopen if you still want help. thanks.
