### ISSUE TITLE
Samsung Galaxy J3 SM-J320M/DS (j3xlte)

### ISSUE THREAD

**Issue by mathispo** [Lanchon/REPIT#93]
I'd be glad if you can port it to this model.

All the specs are here -> https://www.phonemore.com/specs/samsung/galaxy-j3/sm-j320mds/

The rom and the recovery that I use is this one -> https://forum.xda-developers.com/galaxy-j3-2016/development/rom-lineageos-14-1-samsung-galaxy-j3-t3667015

The partition layout is stock.

[repit-dump.log](https://github.com/Lanchon/REPIT/files/3382491/repit-dump.log)

**Comment by Lanchon** [comment]
hi,

thanks!

i worry that phones could be protected by a signed GPT.

read the issues here tagged with or discussing signed GPTs. try running `strings` on your bootloaders and see what you find (or post the bootloader images here). decide whether you want to run the risk.

**Comment by mathispo** [comment]
I'm sorry, I no longer have this phone.

**Comment by Lanchon** [comment]
sorry i kept you waiting so long.

thanks!
