### ISSUE TITLE
Asus Nexus 7 (2012) (grouper)

### ISSUE THREAD

**Issue by Gene1968** [Lanchon/REPIT#99]
[repit-dump.log](https://github.com/Lanchon/REPIT/files/3825821/repit-dump.log)

Device:  "Nexus 7" (2012 model, not 2013),  Codename:  Grouper
Recovery:  TWRP 3.3.1.0 official
Kernel:  3.1.10-nougat-g72fc28a
ROM:  at the moment Resurection 712 (RR-N-v5.8.5-20171216-grouper-Unofficial.zip).  But can't fit GApps ARM 7 Pico.
Partition layout is still stock, lots of room in Data.

Thank you if you get a chance to determine the config edit/rename for me!

**Comment by Lanchon** [comment]
hey thanks!

read the issues tagged with signed GPT, then decide if you want to risk a test. if you do i'll port it to your device.

**Comment by Gene1968** [comment]
Okay, I found 2 threads with that label.  I'm not concerned, and willing to take the risk as it's just an older device which was pretty useless on stock anyway.

Thanks for looking at it!

**Comment by Lanchon** [comment]
btw, there's a test you can do with the `strings` command. its on the tagged issue.

**Comment by Lanchon** [comment]
so sorry, this device is very weird and REPIT cannot be ported to it.
it does not have a standard GPT.
please see: https://github.com/Lanchon/REPIT/issues/79

**Comment by Gene1968** [comment]
Thanks anyway!
